---
- name: Ensure group "wheel" exists
  group: name=wheel state=present

- name: Ensure group "power" exists
  group: name=power state=present

- name: Add {{ ansible_ssh_user }} to new groups
  user:
    name: "{{ ansible_ssh_user }}"
    groups: wheel,power
    append: yes

- name: Install openssh server
  package: name=openssh state=installed

- name: Enable sshd
  service: state=started enabled=yes name=sshd

- name: Install pacmatic
  package: name=pacmatic state=installed

- name: Install emacs
  package: name=emacs state=installed

- name: Install graphical packages
  package: name={{item}} state=installed
  with_items:
    - chromium
    - uzbl-tabbed
    - xclip
  when: headless == false

#- name: install chromium-pepper-flash
  #command: yaourt --noconfirm -S chromium-pepper-flash
  # and dtrx

- name: Removing syslinux timeout to one-half second
  lineinfile:
    dest: /boot/syslinux/syslinux.cfg
    state: absent
    regexp: "TIMEOUT"
    
- name: Setting syslinux timeout to one-half second
  lineinfile:
    dest: /boot/syslinux/syslinux.cfg
    state: present
    line: "TIMEOUT 5"
    insertafter: "^PROMPT"

- name: Allow group wheel to use sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    insertafter: "# %wheel ALL=(ALL) NOPASSWD: ALL"
