---
- name: update pacman cache
  pacman: update_cache=yes

- name: Ensure groups exist
  group: name={{item}} state=present
  with_items:
    - power
    - wheel

- name: Add eric to new groups
  user:
    name: "eric"
    groups: wheel,power
    append: yes

- name: Install openssh server
  package: name=openssh state=installed

- name: Enable sshd
  service: state=started enabled=yes name=sshd

- name: install archlinux packages
  package: name={{item}} state=installed
  with_items:
    - pacmatic
    - emacs

#- name: install chromium-pepper-flash
  #command: yaourt --noconfirm -S chromium-pepper-flash
  # and dtrx

- name: Removing syslinux timeout to one-half second
  lineinfile:
    dest: /boot/syslinux/syslinux.cfg
    state: absent
    regexp: "TIMEOUT"
    
- name: Setting syslinux timeout to one-half second
  lineinfile:
    dest: /boot/syslinux/syslinux.cfg
    state: present
    line: "TIMEOUT 5"
    insertafter: "^PROMPT"

- name: Allow group wheel to use sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    insertafter: "# %wheel ALL=(ALL) NOPASSWD: ALL"
