---
- name: install common graphical packages
  package: name={{item}} state=installed
  with_items:
    - dialog
    - rxvt-unicode
    - vlc
    - ristretto
    - tumbler
    - xclip

- name: Install graphical packages
  package: name={{item}} state=installed
  with_items:
    - chromium
    - uzbl-tabbed
  when: ansible_os_family == "Archlinux"

- name: Install graphical packages
  package: name={{item}} state=installed
  with_items:
    - chromium-browser
    - uzbl
  when: ansible_os_family == "Debian"

- name: Remove capslock from xorg keymap
  gsetting: user=eric
            key=org.gnome.desktop.input-sources.xkb-options
            value="['ctrl:nocaps']"

- name: Change dconf settings
  gsetting: "user=eric
    key={{ item.value.key }}
    value={{ item.value.value }}"
  with_dict: "{{ gsettings }}"
  ignore_errors: true

- include: gnome.yml
# - include: bspwm.yml
