---
- include: archlinux.yml
  when: ansible_os_family == "Archlinux"

- include: ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Set hostname
  hostname: name="{{ hostname }}"

- include: locale.yml

- include: packages.yml

- include: esc.yml
  become: yes
  become_user: "eric"

