---
- include: archlinux.yml
  become: yes
  become_user: root
  when: ansible_os_family == "Archlinux"

- include: ubuntu.yml
  become: yes
  become_user: root
  when: ansible_os_family == "Debian"

- include: locale.yml

- include: packages.yml
  become: yes
  become_user: root

- include: esc.yml

- include: graphical.yml
  become: yes
  become_user: root
  when: graphical is defined
