---
- name: install python-setuptools
  package: state=installed name=python-setuptools

- name: check for pip
  command: which pip
  register: pip
  ignore_errors: yes

- name: install pip
  command: easy_install pip
  when: pip|failed

- name: upgrade virtualenv
  pip: name={{item}} state=latest
  with_items:
    - virtualenv
    - virtualenvwrapper

