---
- name: Install python
  package: state=installed name=python-setuptools

- name: Check for pip
  command: which pip
  register: pip
  ignore_errors: yes

- name: Install pip
  command: easy_install pip
  when: pip|failed

- name: Install virtualenv
  shell: pip install --upgrade {{item}}
  with_items:
    - virtualenv
    - virtualenvwrapper

